# Generated by Django 3.0.3 on 2022-06-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0004_auto_20220604_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Destination',
            new_name='destination',
        ),
    ]
