# Generated by Django 3.0.3 on 2022-06-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0005_auto_20220604_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='DepartureDate',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='ReturnDate',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
