# Generated by Django 3.0.3 on 2022-06-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0006_auto_20220604_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destiny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('d_destination', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_returndate', models.DateField()),
                ('Destiny', models.ManyToManyField(to='flight_app.Destiny')),
                ('p_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.Book')),
            ],
        ),
    ]
